### ISSUE TITLE
AttributeError: 'EmbeddingVocabulary' object has no attribute '_embeddings'

### ISSUE THREAD

**Issue by amanchuan** [liufly/delayed-memory-update-entnet#1]
hi, liu. I don't know why this error:( . my env is python3, i just have changed some code like print()...
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    in_file=FLAGS.embedding_file_path,
  File "/Users/aman/repo/delayed-memory-update-entnet/vocab_processor.py", line 58, in __init__
    self._load_embeddings(in_file, binary=binary)
  File "/Users/aman/repo/delayed-memory-update-entnet/vocab_processor.py", line 77, in _load_embeddings
    self._embeddings[self._mapping[word], :] = emb
AttributeError: 'EmbeddingVocabulary' object has no attribute '_embeddings'

**Comment by Jorigorn** [comment]
@revierJ Save error here.
I am using tensorflow 1.4.1 python2.7, the same environment as readme.

**Comment by Jorigorn** [comment]
Just figured out the problem,
it assumed the first line of embedding file contain the vocabulary size and dimension size.
So add that to the embedding file :  

**sed -i '1i 1917494 300' /data/glove/glove.42B.300d.txt**


Then:

delayed-memory-update-entnet# python main.py --embedding_file /data/glove/glove.42B.300d.txt
/root/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-08-30 16:15:22,189 - root - INFO - main.py --embedding_file /data/glove/glove.42B.300d.txt
2018-08-30 16:15:22,190 - root - INFO - Started Task: Sentihood
2018-08-30 16:15:22,191 - root - INFO - {'batch_size': 128,
 'case_folding': True,
 'data_dir': 'data/sentihood/',
 'embedding_file_path': '/data/glove/glove.42B.300d.txt',
 'embedding_size': 20,
 'entnet_input_keep_prob': 0.8,
 'entnet_output_keep_prob': 1.0,
 'entnet_state_keep_prob': 1.0,
 'epochs': 800,
 'evaluation_interval': 1,
 'final_layer_keep_prob': 0.8,
 'l2_final_layer': 0.001,
 'learning_rate': 0.05,
 'max_grad_norm': 5.0,
 'n_cpus': 6,
 'n_keys': 7,
 'n_tied': 2,
 'opt': 'ftrl',
 'random_state': 67,
 'sentence_len': 50,
 'task': 'Sentihood',
 'update_embeddings': False}
2018-08-30 16:15:22.191501: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-08-30 16:15:29,286 - root - INFO - Max sentence len: 50
2018-08-30 16:15:29,294 - root - INFO - Max target size: ....

**Comment by liufly** [comment]
Thanks @Jorigorn. And apologies for not clarifying this. Will put it in the README.

**Comment by liufly** [comment]
Thank you both @Jorigorn and @revierJ 
README updated.
